// Built using Hyperiux Vault: https://vault.hyperiux.com

// Verbatim from 21st.dev (~/.cursor/skills/component-library/prompts/interactive-list-preview-and-agent-plan-integration.md)
// with three changes, per docs/FRONTEND.md §4.3:
//   1. optional `onSelect(index)` prop, wired to onClick on each <tr>; the row is also focusable
//      (tabIndex 0) and Enter/Space call onSelect, so the detail is reachable from the keyboard
//   2. the third <td> (blank in the source) renders the optional `item.status`
//   3. `services` accepts React nodes as well as strings (for the red tool-call span)
//   4. the preview is an opaque card (hairline, shadow) at its natural pixel size that follows
//      the cursor, sitting to the right of it and vertically centred on it, flipped to the left
//      when it would run past the list's edge and clamped to the list and the viewport so it is
//      never cut off. It paints above the rows (z-20) so it is always legible. Below lg and on
//      touch it is not rendered. `item.spanGutter` is kept for the attack preview row's colspan.
//   5. `item.preview` (SVG markup) is inlined instead of loaded through <img>, so chart text can
//      use the page's web font.
// Plus, as the prompt instructs ("Fill image assets with Unsplash stock images you know exist"),
// the DEFAULT_ITEMS base64 JPEGs are replaced by Unsplash URLs.
//
// Provenance caveat: the chat transcript lost the original paste, so this file was reconstructed
// from working context rather than copied byte-exact. Paint order was then corrected against the
// reference screenshot (ref-interactive-list-preview-hover.png): preview image below the
// highlight bar (z-0), table text above it (relative z-10), so hovered text reads black on the bar.
// Change 4 moves the preview above the bar (z-20): it lives in the gutter, so it never covers text.

"use client";

import { useEffect, useRef, useState } from "react";
import type { MouseEvent as ReactMouseEvent, ReactNode } from "react";
import gsap from "gsap";

export interface InteractiveListItem {
  client: string;
  platform?: string;
  status?: string;
  services: string | ReactNode;
  /** Image URL for the hover card. Ignored when `preview` is set. */
  img?: string;
  /** Inline SVG markup for the hover card; trusted, generated by this app. */
  preview?: string;
  /** Let the meta cell extend across the gutter (for rows whose meta is long and have no preview). */
  spanGutter?: boolean;
}

export interface InteractiveListPreviewProps {
  items?: InteractiveListItem[];
  /** Scale multiplier for the hover preview card. */
  imageSize?: number;
  /** Preview image reveal / hide duration (seconds). */
  duration?: number;
  /** Highlight bar + row text transition smoothing (seconds). */
  smoothness?: number;
  /** Pointer-follow smoothing; higher tracks faster. */
  lerp?: number;
  /** Background color of the list surface. */
  bgColor?: string;
  className?: string;
  onSelect?: (index: number) => void;
}

const DEFAULT_IMAGE_Z_INDEX = 10;
const DEFAULT_IMAGE_SIZE = 1;
const DEFAULT_DURATION = 0.6;
const DEFAULT_SMOOTHNESS = 0.35;
const DEFAULT_LERP = 0.18;
const u = (id: string) => `https://images.unsplash.com/${id}?w=800&q=80&auto=format&fit=crop`;
const DEFAULT_ITEMS: InteractiveListItem[] = [
  { client: "AURORA UI", platform: "NEXT.JS", services: "Motion Design, GSAP, Page Transitions, UI Systems", img: u("photo-1518770660439-4636190af475") },
  { client: "NEON FLOW", platform: "REACT", services: "Interactive UI, Scroll Animations, Effects Library", img: u("photo-1550745165-9bc0b252726f") },
  { client: "GLASSMORPH", platform: "NEXT.JS", services: "Glass UI, Components, Motion Architecture", img: u("photo-1451187580459-43490279c0fa") },
  { client: "VOID SYSTEM", platform: "CUSTOM WEBGL", services: "Shaders, Creative Development, Visual Effects", img: u("photo-1526374965328-7f61d4dc18c5") },
  { client: "HYPER SCROLL", platform: "FRAMER MOTION", services: "Scroll Storytelling, Motion Systems, Interactions", img: u("photo-1519389950473-47ba0277781c") },
  { client: "KINETIC LAB", platform: "THREE.JS", services: "3D Interfaces, Motion UI, WebGL Experiences", img: u("photo-1531297484001-80022131f5a1") },
  { client: "PIXEL GRID", platform: "TAILWIND CSS", services: "Design Systems, UI Engineering, Responsive Layouts", img: u("photo-1558494949-ef010cbdcc31") },
  { client: "MOTION CORE", platform: "HEADLESS CMS", services: "Reusable Components, Motion Engine, Performance", img: u("photo-1504384308090-c894fdcc538d") },
  { client: "INTERFACE X", platform: "NEXT.JS", services: "Immersive UI, Creative Coding, Transitions, Effects", img: u("photo-1515879218367-8466d910aaa4") },
  { client: "HYPERIUX", platform: "UI LIBRARY", services: "Animations, Interactive Components, Futuristic Experiences", img: u("photo-1487058792275-0ad4aaf24ca7") },
];

const BASE_IMAGE_WIDTH_PX = 300;
const BASE_IMAGE_HEIGHT_PX = 260;
// Title takes most of the row; the meta column is two short facts.
const TITLE_PCT = 64;
// Gap between the cursor and the card's near edge, and the margin kept from the viewport edges.
const CURSOR_GAP_PX = 28;
const VIEWPORT_MARGIN_PX = 12;
const ACTIVE_ROW_TEXT_COLOR = "#000000";
const INACTIVE_ROW_TEXT_COLOR = "#ffffff";
const IMAGE_HIDDEN_CLIP_PATH = "inset(50%)";
const IMAGE_VISIBLE_CLIP_PATH = "inset(0%)";
const IMAGE_VISIBILITY_HIDDEN = "hidden";
const IMAGE_VISIBILITY_VISIBLE = "visible";

function clampNumber(value: number, min: number, max: number, fallback: number) {
  const number = Number(value);
  if (!Number.isFinite(number)) return fallback;
  return Math.min(Math.max(number, min), max);
}

/**
 * @typedef {Object} InteractiveListPreviewCompProps
 * @property {InteractiveListItem[]} items
 */

/** @param {InteractiveListPreviewCompProps} props */
export default function InteractiveListPreview({
  items = DEFAULT_ITEMS,
  imageSize = DEFAULT_IMAGE_SIZE,
  duration = DEFAULT_DURATION,
  smoothness = DEFAULT_SMOOTHNESS,
  lerp = DEFAULT_LERP,
  bgColor = "#171717",
  className = "",
  onSelect,
}: InteractiveListPreviewProps) {
  const imageRefs = useRef<any[]>([]);
  const imageContainerRef = useRef<any>(null);
  const tableRef = useRef<any>(null);
  const highlightRef = useRef<any>(null);
  const rowRefs = useRef<Record<number, any>>({});
  const pendingLeaveRef = useRef<Record<number, boolean>>({});
  const tweenGenerationRef = useRef<Record<number, number>>({});
  const activeIndexRef = useRef<number | null>(null);
  const zIndexRef = useRef(DEFAULT_IMAGE_Z_INDEX);
  const pointerTargetRef = useRef({ x: 0, y: 0 });
  const pointerCurrentRef = useRef({ x: 0, y: 0 });
  const placedRef = useRef(false);
  const wrapRef = useRef<HTMLDivElement | null>(null);
  const [isCoarsePointer, setIsCoarsePointer] = useState(false);
  const reduceMotionRef = useRef(
    typeof window !== "undefined" &&
      (window.matchMedia?.("(prefers-reduced-motion: reduce)")?.matches ?? false)
  );
  const safeImageSize = clampNumber(imageSize, 0.5, 2, DEFAULT_IMAGE_SIZE);
  const safeDuration = clampNumber(duration, 0.1, 2, DEFAULT_DURATION);
  const safeSmoothness = clampNumber(smoothness, 0.05, 1.5, DEFAULT_SMOOTHNESS);
  const safeLerp = clampNumber(lerp, 0.02, 1, DEFAULT_LERP);

  useEffect(() => {
    const mq = window.matchMedia?.("(prefers-reduced-motion: reduce)");
    if (!mq) return;

    const onChange = (event: MediaQueryListEvent) => {
      reduceMotionRef.current = event.matches;
    };

    reduceMotionRef.current = mq.matches;
    mq.addEventListener?.("change", onChange);
    return () => mq.removeEventListener?.("change", onChange);
  }, []);

  useEffect(() => {
    const mq = window.matchMedia("(pointer: coarse)");
    const update = () => setIsCoarsePointer(mq.matches);
    update();
    mq.addEventListener("change", update);
    return () => mq.removeEventListener("change", update);
  }, []);

  // The card only exists at lg and up; below that there is no room beside the cursor.
  const [isWide, setIsWide] = useState(false);
  useEffect(() => {
    const mq = window.matchMedia("(min-width: 1024px)");
    const update = () => setIsWide(mq.matches);
    update();
    mq.addEventListener("change", update);
    return () => mq.removeEventListener("change", update);
  }, []);

  useEffect(() => {
    let frameId: number;

    const tick = () => {
      const imageContainer = imageContainerRef.current;

      if (imageContainer) {
        const current = pointerCurrentRef.current;
        const target = pointerTargetRef.current;

        if (reduceMotionRef.current || !placedRef.current) {
          // First placement (or reduced motion): no easing, so the card never flies in from a corner.
          current.x = target.x;
          current.y = target.y;
          placedRef.current = true;
        } else {
          current.x += (target.x - current.x) * safeLerp;
          current.y += (target.y - current.y) * safeLerp;
        }

        gsap.set(imageContainer, {
          x: current.x,
          y: current.y,
        });
      }

      frameId = requestAnimationFrame(tick);
    };

    frameId = requestAnimationFrame(tick);

    return () => cancelAnimationFrame(frameId);
  }, [safeLerp]);

  useEffect(() => {
    imageRefs.current.forEach((imageElement: any) => {
      if (!imageElement) return;

      if (reduceMotionRef.current) {
        // Reduced-motion: opacity only — keep full clip, start hidden.
        gsap.set(imageElement, {
          clipPath: IMAGE_VISIBLE_CLIP_PATH,
          opacity: 0,
          visibility: IMAGE_VISIBILITY_HIDDEN,
        });
      } else {
        gsap.set(imageElement, {
          clipPath: IMAGE_HIDDEN_CLIP_PATH,
          visibility: IMAGE_VISIBILITY_HIDDEN,
        });
      }
    });

    if (!highlightRef.current) return;

    gsap.set(highlightRef.current, {
      opacity: 0,
      y: 0,
      height: 0,
    });
  }, []);

  /** @param {number} index */
  const getNextTweenGeneration = (index: number) => {
    tweenGenerationRef.current[index] =
      (tweenGenerationRef.current[index] || 0) + 1;

    return tweenGenerationRef.current[index];
  };

  /**
   * @param {number} index
   * @param {HTMLDivElement|null} element
   */
  const setImageRef = (index: number, element: HTMLDivElement | null) => {
    imageRefs.current[index] = element;
  };

  /**
   * @param {number} index
   * @param {string} color
   */
  const setRowTextColor = (index: number, color: string) => {
    const rowElement = rowRefs.current[index];

    if (!rowElement) return;

    gsap.to(rowElement.querySelectorAll("td"), {
      color,
      duration: safeSmoothness,
      ease: "power2.out",
      overwrite: "auto",
    });
  };

  /** @param {HTMLTableRowElement|null} rowElement */
  const moveHighlightToRow = (rowElement: HTMLTableRowElement | null) => {
    const tableElement = tableRef.current;
    const highlightElement = highlightRef.current;

    if (!tableElement || !highlightElement || !rowElement) return;

    const tableBounds = tableElement.getBoundingClientRect();
    const rowBounds = rowElement.getBoundingClientRect();

    gsap.to(highlightElement, {
      y: rowBounds.top - tableBounds.top,
      height: rowBounds.height,
      opacity: 1,
      duration: safeSmoothness,
      ease: "power3.out",
      overwrite: "auto",
    });
  };

  const hideHighlight = () => {
    if (!highlightRef.current) return;

    gsap.to(highlightRef.current, {
      opacity: 0,
      duration: safeSmoothness,
      ease: "power3.out",
      overwrite: "auto",
    });
  };

  /** @param {number} index */
  const revealImage = (index: number) => {
    const imageElement = imageRefs.current[index];

    if (!imageElement) return;

    const generation = getNextTweenGeneration(index);

    pendingLeaveRef.current[index] = false;
    zIndexRef.current += 1;

    if (reduceMotionRef.current) {
      gsap.killTweensOf(imageElement);
      gsap.set(imageElement, {
        zIndex: zIndexRef.current,
        clipPath: IMAGE_VISIBLE_CLIP_PATH,
        visibility: IMAGE_VISIBILITY_VISIBLE,
      });
      gsap.to(imageElement, {
        opacity: 1,
        duration: 0.2,
        ease: "power2.out",
        overwrite: "auto",
      });
      return;
    }

    gsap.killTweensOf(imageElement);
    gsap.set(imageElement, {
      zIndex: zIndexRef.current,
      visibility: IMAGE_VISIBILITY_VISIBLE,
    });

    gsap.to(imageElement, {
      clipPath: IMAGE_VISIBLE_CLIP_PATH,
      duration: safeDuration,
      ease: "power4.out",
      overwrite: "auto",
      onComplete: () => {
        if (
          pendingLeaveRef.current[index] &&
          tweenGenerationRef.current[index] === generation
        ) {
          hideImage(index);
        }
      },
    });
  };

  /** @param {number} index */
  const hideImage = (index: number) => {
    const imageElement = imageRefs.current[index];

    if (!imageElement) return;

    if (reduceMotionRef.current) {
      gsap.killTweensOf(imageElement);
      gsap.to(imageElement, {
        opacity: 0,
        duration: 0.2,
        ease: "power2.out",
        overwrite: "auto",
        onComplete: () => {
          gsap.set(imageElement, { visibility: IMAGE_VISIBILITY_HIDDEN });
        },
      });
      return;
    }

    gsap.killTweensOf(imageElement);
    gsap.to(imageElement, {
      clipPath: IMAGE_HIDDEN_CLIP_PATH,
      duration: safeDuration,
      ease: "power4.out",
      overwrite: "auto",
      onComplete: () => {
        gsap.set(imageElement, { visibility: IMAGE_VISIBILITY_HIDDEN });
      },
    });
  };

  /**
   * @param {ReactMouseEvent<HTMLTableRowElement>} event
   * @param {number} index
   */
  const handleRowMouseEnter = (
    event: ReactMouseEvent<HTMLTableRowElement>,
    index: number
  ) => {
    if (isCoarsePointer) return;

    const previousIndex = activeIndexRef.current;

    if (previousIndex !== null && previousIndex !== index) {
      setRowTextColor(previousIndex, INACTIVE_ROW_TEXT_COLOR);
    }

    activeIndexRef.current = index;
    setRowTextColor(index, ACTIVE_ROW_TEXT_COLOR);
    moveHighlightToRow(event.currentTarget);
    revealImage(index);
  };

  /** @param {number} index */
  const handleRowMouseLeave = (index: number) => {
    if (isCoarsePointer) return;

    pendingLeaveRef.current[index] = true;

    if (activeIndexRef.current === index) {
      activeIndexRef.current = null;
    }

    setRowTextColor(index, INACTIVE_ROW_TEXT_COLOR);
    hideHighlight();
    hideImage(index);
  };

  /**
   * The card's target position, in the wrapper's coordinates: right of the cursor and centred on
   * it, flipped to the left when the right side has no room, then clamped to the wrapper's width
   * and to whatever part of the wrapper is inside the viewport, so no edge is ever cut off.
   * @param {ReactMouseEvent<HTMLElement>} event
   */
  const handleContainerMouseMove = (event: ReactMouseEvent<HTMLElement>) => {
    if (isCoarsePointer) return;
    const wrap = wrapRef.current;
    if (!wrap) return;

    const w = BASE_IMAGE_WIDTH_PX * safeImageSize;
    const h = BASE_IMAGE_HEIGHT_PX * safeImageSize;
    const b = wrap.getBoundingClientRect();
    const px = event.clientX - b.left;
    const py = event.clientY - b.top;

    let x = px + CURSOR_GAP_PX;
    if (x + w > b.width) x = px - CURSOR_GAP_PX - w;
    x = Math.min(Math.max(x, 0), Math.max(0, b.width - w));

    const minY = Math.max(0, VIEWPORT_MARGIN_PX - b.top);
    const maxY = Math.min(b.height - h, window.innerHeight - VIEWPORT_MARGIN_PX - b.top - h);
    let y = py - h / 2;
    y = Math.min(Math.max(y, minY), Math.max(minY, maxY));

    pointerTargetRef.current = { x, y };
  };

  const handleContainerMouseLeave = () => {
    // Next hover starts fresh at the cursor instead of easing over from wherever the card was left.
    placedRef.current = false;
  };

  // When the items change under the pointer (a new cycle lands while a row is hovered), the rows
  // remount with default white text while the white bar stays where it was: white on white. Drop
  // the hover state; the next pointer move re-hovers cleanly.
  useEffect(() => {
    const active = activeIndexRef.current;
    if (active === null) return;
    activeIndexRef.current = null;
    if (highlightRef.current) gsap.set(highlightRef.current, { opacity: 0 });
    imageRefs.current.forEach((el: any) => el && gsap.set(el, { visibility: IMAGE_VISIBILITY_HIDDEN, clipPath: IMAGE_HIDDEN_CLIP_PATH }));
    Object.values(rowRefs.current).forEach((row: any) => row && gsap.set(row.querySelectorAll("td"), { color: INACTIVE_ROW_TEXT_COLOR }));
  }, [items]);

  const imageWidthPx = BASE_IMAGE_WIDTH_PX * safeImageSize;
  const imageHeightPx = BASE_IMAGE_HEIGHT_PX * safeImageSize;

  return (
    <section
      className={`relative w-full overflow-hidden text-white ${className}`}
      style={{ backgroundColor: bgColor }}
      onMouseMove={handleContainerMouseMove}
      onMouseLeave={handleContainerMouseLeave}
    >
      <div className="relative z-10 mx-auto w-full max-w-6xl px-6 pb-2 pt-3 md:px-10">
        {/* min-h keeps a one-row list tall enough to hold the card. */}
        <div ref={wrapRef} className="relative min-h-[19rem]">
          {/* The bar bleeds 20px past the table on both ends so hovered text never sits on its edge. */}
          <div
            ref={highlightRef}
            className="pointer-events-none absolute -left-5 top-0 w-[calc(100%+2.5rem)] bg-white mix-blend-difference"
          />

          {/* The preview card. Positioned from the wrapper's top-left by the gsap x/y that the
              pointer handler feeds (see handleContainerMouseMove). Above the rows (z-20) so it is
              always readable, even over the highlight bar. */}
          <div
            ref={imageContainerRef}
            className="pointer-events-none absolute left-0 top-0 z-20"
            style={{
              width: `${imageWidthPx}px`,
              height: `${imageHeightPx}px`,
              display: isCoarsePointer || !isWide ? "none" : undefined,
            }}
          >
            {items.map((item, index) => {
              // Rows with nothing to show (attack preview rows) get no card at all; revealImage()
              // already no-ops on a missing ref, so hovering them only moves the highlight bar.
              if (!item.preview && !item.img) return null;
              return (
                <div
                  key={`${item.client}-${index}`}
                  ref={(element) => setImageRef(index, element)}
                  className="absolute inset-0 overflow-hidden rounded-lg border border-[var(--border)] bg-[var(--card)] shadow-[0_16px_48px_rgba(0,0,0,0.55)]"
                  style={{ visibility: IMAGE_VISIBILITY_HIDDEN }}
                >
                  {item.preview ? (
                    <div
                      className="h-full w-full [&>svg]:h-full [&>svg]:w-full"
                      // Trusted: generated by this app from its own records (see lib/previewSvg.ts).
                      dangerouslySetInnerHTML={{ __html: item.preview }}
                    />
                  ) : (
                    <img
                      src={item.img}
                      alt={item.client}
                      className="h-full w-full"
                      style={{ objectFit: "contain" }}
                      draggable={false}
                    />
                  )}
                </div>
              );
            })}
          </div>

          {/* Column widths are fixed so rows stay one line tall and the columns share edges.
              Text color on every <td> is owned by the gsap tween (white <-> black on hover), so the
              secondary text is dimmed with opacity, which the tween cannot overwrite. */}
          <table ref={tableRef} className="tabular relative z-10 w-full table-fixed border-collapse">
            <colgroup>
              <col style={{ width: `${TITLE_PCT}%` }} />
              <col style={{ width: 0 }} />
              <col />
            </colgroup>
            <tbody>
              {items.map((item, index) => (
                <tr
                  key={`${item.client}-${index}`}
                  ref={(element) => {
                    rowRefs.current[index] = element;
                  }}
                  className="cursor-pointer border-t border-white/10 text-white last:border-b"
                  role={onSelect ? "button" : undefined}
                  aria-label={onSelect ? item.client : undefined}
                  onMouseEnter={(event) => handleRowMouseEnter(event, index)}
                  onMouseLeave={() => handleRowMouseLeave(index)}
                  onClick={() => onSelect?.(index)}
                  tabIndex={onSelect ? 0 : undefined}
                  onKeyDown={(event) => {
                    // Only when the row itself is focused: a button inside the row (the preview's ×) keeps its own keys.
                    if (!onSelect || event.target !== event.currentTarget) return;
                    if (event.key !== "Enter" && event.key !== " ") return;
                    event.preventDefault();
                    onSelect(index);
                  }}
                >
                  <td
                    className="truncate py-4 pr-6 text-[13px] font-medium uppercase tracking-[0.08em] md:py-5"
                    title={item.client}
                  >
                    {item.client}
                  </td>
                  {!item.spanGutter && <td className="p-0" aria-hidden />}
                  <td
                    className="py-4 text-right text-[12px] uppercase tracking-[0.08em] md:py-5"
                    colSpan={item.spanGutter ? 2 : 1}
                  >
                    <span className="inline-flex max-w-full flex-wrap items-baseline justify-end gap-x-3 gap-y-1 whitespace-nowrap">
                      {item.platform && <span className="opacity-60">{item.platform}</span>}
                      {item.status && <span>{item.status}</span>}
                      <span className="opacity-80">{item.services}</span>
                    </span>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </section>
  );
}
